name: Node Application Continuous Integration 
on: push
jobs:
  build-node:
    name: Bulid and run Node Project
    runs-on: ubuntu-latest
    container: node:21
    steps:
      - run: node --version
        name: Check Node version
      - run: npm --version
        name: Check npm version
      - uses: actions/checkout@v4
        name: Checkout code from Github using checkout vartion 4
      - run: npm install
        name: Install npm packages
      - run: node index.js
        name: run node application 
